################################# Default configuration ###################
baseURL = "https://chienvu.com"
title = "Domino Media"
theme = "meghna-hugo"
themesDir = "../.."
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css2?family=Noto+Sans:wght@400;700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

################### English Navigation ########################


[[Languages.en.menu.main]]
name = "Services"
url = "#services"
weight = 2

[[Languages.en.menu.main]]
name = "About Us"
url = "#about"
weight = 1

[[Languages.en.menu.main]]
name = "Portfolio"
url = "#portfolio"
weight = 3


[[Languages.en.menu.main]]
name = "Pricing"
url = "#pricing"
weight = 5


[[Languages.en.menu.main]]
name = "Contact"
url = "#contact"
weight = 7


################### VN Navigation ########################

[[Languages.vn.menu.main]]
name = "Dịch Vụ"
url = "#services"
weight = 2

[[Languages.vn.menu.main]]
name = "Giới Thiệu"
url = "#about"
weight = 1

[[Languages.vn.menu.main]]
name = "Sản Phẩm"
url = "#portfolio"
weight = 3


[[Languages.vn.menu.main]]
name = "Giá Thành"
url = "#pricing"
weight = 5


[[Languages.vn.menu.main]]
name = "Liên Hệ"
url = "#contact"
weight = 7


############################# Default Parameters ##########################
[params]
logo = "images/logo.png"
# Meta data
title = "Domino Media Vietnam"
description = "Digital Solution in Photography, Videography and Dronography "
image = "https://www.flickr.com/photos/188221175@N02/50192773838/in/dateposted/"
author = "Chien Vu"
# Google Analytics
google_analytics_id = "" # Your ID
# post share
post_share = true


# preloader
[params.preloader]
enable = false
preloader = "images/logo.png"

# cookies
[params.cookies]
enable = false
expire_days = 2

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

############################# social icons ##########################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "https://www.facebook.com/DominoMedia.vn"

[[params.social]]
icon = "ti-youtube" # themify icon pack : https://themify.me/themify-icons
link = "https://www.youtube.com/channel/UCoV6JTPR8QMj3Sq6n6Pzs0g"

[[params.social]]
icon = "ti-instagram" # themify icon pack : https://themify.me/themify-icons
link = "https://www.instagram.com/chienvv/"

[[params.social]]
icon = "ti-dribbble" # themify icon pack : https://themify.me/themify-icons
link = "https://www.facebook.com/chien991992"



################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
copyright = "© 2021 Domino Media"

################################ vietnamese Language ########################
[Languages.vn]
languageName = "Vn"
languageCode = "vn-vn"
contentDir = "content/vietnamese"
weight = 2
home = "Accueil"
copyright = "© 2021 Bản quyền thuộc về Domino Media"
